version: "3"
services:
  app:
    build: .
    container_name: inst-gallery
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: always
